# Generated by Django 5.1 on 2024-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedbacksession_nps_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksession',
            name='nps_score',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
