# Generated by Django 5.0.6 on 2025-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_criteria_course_task_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
