# Generated by Django 5.0.6 on 2025-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_criteria_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksession',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='staff_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
