# Generated by Django 5.2.7 on 2025-10-10 12:25

import coffee.home.security.encryption
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_feedbacksession_options_alter_course_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackcriteria',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('azure_ai', 'Azure AI'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('api_key', coffee.home.security.encryption.EncryptedTextField(blank=True, default='')),
                ('endpoint', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'is_active'], name='home_provid_type_e7de4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_name', models.CharField(max_length=200)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llm_models', to='home.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'is_active'], name='home_llmmod_provide_a24e21_idx'), models.Index(fields=['external_name'], name='home_llmmod_externa_8de9a5_idx')],
            },
        ),
    ]
