# Generated by Django 5.2.7 on 2025-10-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_feedbackcriteria_unique_together_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='llm_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='llm', to='home.llmmodel'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='llm',
            field=models.TextField(blank=True, help_text='Deprecated', null=True),
        ),
    ]
