# Generated by Django 5.2.7 on 2025-10-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_criteria_llm_fk_alter_criteria_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
