# Generated by Django 5.2.7 on 2025-10-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_llmmodel_is_default'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='LLMProvider',
        ),
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'verbose_name': 'LLM Model', 'verbose_name_plural': 'LLM Models'},
        ),
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'verbose_name': 'LLM Provider', 'verbose_name_plural': 'LLM Providers'},
        ),
        migrations.AlterModelTable(
            name='llmprovider',
            table='home_provider',
        ),
    ]
