# Generated by Django 5.2.7 on 2025-10-14 09:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_provider_llmprovider_alter_llmmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksession',
            name='llm_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_modell', to='home.llmmodel'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_provider', to='home.llmprovider'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='tokens_used_completion',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='tokens_used_system',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='tokens_used_user',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='reset_anchor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='token_limit',
            field=models.PositiveBigIntegerField(default=0, help_text='Max. Tokens per Interval. 0 = No Limit.'),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='token_reset_interval',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Reset-Interval (e.g. 24h).'),
        ),
        migrations.AddIndex(
            model_name='feedbacksession',
            index=models.Index(fields=['provider', 'timestamp'], name='idx_fbsess_provider_timestamp'),
        ),
    ]
