# Generated by Django 5.2.7 on 2025-10-15 08:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_feedbacksession_llm_model_feedbacksession_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCriterionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_criterion_id', models.UUIDField(db_index=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('llm_external_name', models.TextField(blank=True, null=True)),
                ('tokens_used_system', models.PositiveBigIntegerField(default=0)),
                ('tokens_used_user', models.PositiveBigIntegerField(default=0)),
                ('tokens_used_completion', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='feedbacksession',
            name='idx_fbsess_provider_timestamp',
        ),
        migrations.RemoveField(
            model_name='feedbacksession',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='feedbacksession',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='feedbacksession',
            name='tokens_used_completion',
        ),
        migrations.RemoveField(
            model_name='feedbacksession',
            name='tokens_used_system',
        ),
        migrations.RemoveField(
            model_name='feedbacksession',
            name='tokens_used_user',
        ),
        migrations.AddField(
            model_name='feedbackcriterionresult',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion_results', to='home.llmmodel'),
        ),
        migrations.AddField(
            model_name='feedbackcriterionresult',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion_results', to='home.llmprovider'),
        ),
        migrations.AddField(
            model_name='feedbackcriterionresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_results', to='home.feedbacksession'),
        ),
        migrations.AddIndex(
            model_name='feedbackcriterionresult',
            index=models.Index(fields=['llm_model', 'created_at'], name='idx_crit_llm_time'),
        ),
        migrations.AddIndex(
            model_name='feedbackcriterionresult',
            index=models.Index(fields=['provider', 'created_at'], name='idx_crit_provider_time'),
        ),
        migrations.AddConstraint(
            model_name='feedbackcriterionresult',
            constraint=models.UniqueConstraint(fields=('session', 'client_criterion_id'), name='uq_critresult_session_clientid'),
        ),
    ]
