# Generated by Django 5.2.7 on 2025-10-15 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_feedbackcriterionresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcriterionresult',
            options={'verbose_name': 'Feedback Criteria Result', 'verbose_name_plural': 'Feedback Criteria Results'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksession',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Feedback Session', 'verbose_name_plural': 'Feedback Sessions'},
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='reset_anchor_at',
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
