# Generated by Django 5.2.7 on 2025-10-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_feedbackcriterionresult_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacksession',
            old_name='nps_score',
            new_name='helpfulness_score',
        ),
    ]
