# Generated by Django 5.2.7 on 2025-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_nps_score_feedbacksession_helpfulness_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksession',
            name='helpfulness_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
