# Generated by Django 5.2.7 on 2025-10-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_feedbacksession_helpfulness_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcriterionresult',
            name='generation_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
