apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-postgres-deployment
  namespace: fbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.4
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: feedback-app-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: feedback-app-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: feedback-app-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: feedback-app-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-app-postgres-service
  namespace: fbapp
spec:
  type: NodePort
  selector:
    app: postgres # Expose externally
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30084
