# Generated by Django 5.1 on 2024-08-22 07:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=250)),
                ('study_programme', models.CharField(max_length=250)),
                ('chair', models.CharField(max_length=250)),
                ('course_name', models.CharField(max_length=250)),
                ('course_number', models.CharField(blank=True, max_length=250)),
                ('term', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('course_context', models.TextField(blank=True, max_length=65535, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['faculty'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('llm', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('sequels', models.JSONField(blank=True, default=dict, null=True)),
                ('tag', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Criteria',
                'verbose_name_plural': 'Criteria',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.TextField()),
                ('feedback_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('task_context', models.TextField(blank=True, max_length=65535, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
            options={
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.criteria')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.feedback')),
            ],
            options={
                'verbose_name': 'Feedback Criteria',
                'verbose_name_plural': 'Feedback Criteria',
                'ordering': ['rank'],
                'unique_together': {('feedback', 'criteria')},
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='criteria_set',
            field=models.ManyToManyField(through='home.FeedbackCriteria', to='home.criteria'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.task'),
        ),
    ]
