# Generated by Django 5.1 on 2024-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksession',
            name='nps_score',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
