# Generated by Django 5.1 on 2025-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0003_alter_feedbacksession_nps_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='managing_groups',
            field=models.ManyToManyField(blank=True, related_name='courses_managed', to='auth.group'),
        ),
    ]
