# Generated by Django 5.1 on 2025-01-24 12:56

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_managing_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='course',
            field=models.ForeignKey(default=home.models.get_default_course, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='home.course'),
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=home.models.get_default_course, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.course'),
        ),
    ]
