# Generated by Django 5.0.6 on 2025-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedbacksession_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksession',
            name='nps_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
