# Generated by Django 5.1.5 on 2025-02-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0008_alter_feedbacksession_nps_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='managing_groups',
        ),
        migrations.AddField(
            model_name='course',
            name='editing_groups',
            field=models.ManyToManyField(blank=True, related_name='editable_courses', to='auth.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='viewing_groups',
            field=models.ManyToManyField(blank=True, related_name='viewable_courses', to='auth.group'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.course'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.feedback'),
        ),
    ]
