# Generated by Django 5.2.4 on 2025-07-24 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0009_remove_course_managing_groups_course_editing_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacksession',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='chair',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_programme',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='title',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='feedbackcriteria',
            name='rank',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='session_key',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='staff_user',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active', 'faculty'], name='idx_course_active_faculty'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['faculty', 'study_programme'], name='idx_course_faculty_programme'),
        ),
        migrations.AddIndex(
            model_name='criteria',
            index=models.Index(fields=['course', 'active'], name='idx_criteria_course_active'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['course', 'active'], name='idx_feedback_course_active'),
        ),
        migrations.AddIndex(
            model_name='feedbackcriteria',
            index=models.Index(fields=['feedback', 'rank'], name='idx_fbcrit_feedback_rank'),
        ),
        migrations.AddIndex(
            model_name='feedbacksession',
            index=models.Index(fields=['course', 'timestamp'], name='idx_fbsess_course_timestamp'),
        ),
        migrations.AddIndex(
            model_name='feedbacksession',
            index=models.Index(fields=['feedback', 'timestamp'], name='idx_fbsess_feedback_timestamp'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['course', 'active'], name='idx_task_course_active'),
        ),
    ]
