name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: coffee
          POSTGRES_USER: coffee
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U coffee" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          DB_ENGINE: django.db.backends.postgresql
          DB_NAME: coffee
          DB_USERNAME: coffee
          DB_PASS: secret
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py migrate --noinput
          python manage.py test

